spring:
  application:
      name: itzip
  profiles:
    active: local
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: none
  mongodb:
    embedded:
      version: 4.0.21