spring:
  datasource:
    url: ${LOC_POSTGRESQL_URL}
    username: ${LOC_POSTGRESQL_USERNAME}
    password: ${LOC_POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${LOC_REDIS_HOST}
      port: ${LOC_REDIS_PORT}
      password: ${LOC_REDIS_PASSWORD}

    mongodb:
      host: ${LOC_MONGO_HOST}
      port: ${LOC_MONGO_PORT}
      username: ${LOC_MONGO_USERNAME}
      password: ${LOC_MONGO_PASSWORD}
      database: ${LOC_MONGO_DATABASE}
      authentication-database: ${LOC_MONGO_AUTH}
      uri: ${LOC_MONGO_URI}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${LOC_GAMIL_USERNAME}
    password: ${LOC_GAMIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

jwt:
  accessSecret: ${LOC_JWT_ACCESS_SECRET}
  refreshSecret: ${LOC_JWT_REFRESH_SECRET}
  accessTokenExpire: ${LOC_JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${LOC_JWT_REFRESH_EXPIRE}